import type { Metadata } from "next"
import Link from "next/link"
import type { CSSProperties, ReactNode } from "react"

import { Footer } from "@/components/landing/footer"
import { Nav } from "@/components/landing/nav"
import { ScrollToTop } from "@/components/landing/scroll-to-top"
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"

import { GlossaryIndex } from "./glossary-index"

const CONTENT_WIDTH =
  "mx-auto max-w-[76rem] w-[calc(100%-1rem)] sm:w-[calc(100%-2rem)] md:w-[calc(100%-3rem)] lg:w-[calc(100%-4rem)] xl:w-full"

export const metadata: Metadata = {
  title: "Glossary — Tokokino",
  description:
    "Definitions for every term in the Tokokino editor — from backdrops and device frames to keyframes, portrait modes, and export resolutions.",
}

type GlossaryTerm = {
  term: string
  body: ReactNode
}

const terms: GlossaryTerm[] = [
  {
    term: "Annotation",
    body: "A mark drawn directly over your capture — arrows, shapes, or freehand strokes. Annotations sit on their own layer so you can point at what matters without touching the underlying screenshot.",
  },
  {
    term: "Aspect ratio",
    body: "The width-to-height proportion of the canvas — 16:9, 1:1, 4:3, 9:16, or a custom ratio. Aspect ratio shapes the frame you export into and is independent of the resolution you export at.",
  },
  {
    term: "Asset",
    body: "An image or SVG layered on top of the canvas — a logo, badge, or decorative element. Each asset carries its own position, rotation, z-index, opacity, blend mode, and filter.",
  },
  {
    term: "Auto palette",
    body: "A background generated by sampling the dominant colors from your screenshot, producing a gradient that belongs to the capture instead of clashing with it.",
  },
  {
    term: "Backdrop",
    body: "The layer behind the screenshot but inside the padding. It carries effects (noise, blur, brightness), an optional pattern, and its own filter — the atmosphere your capture sits against.",
  },
  {
    term: "Background",
    body: "The fill behind everything on the canvas. It can be none, a solid color, a gradient, an uploaded image, or an auto-sampled palette drawn from your screenshot.",
  },
  {
    term: "Blend mode",
    body: "How a layer's colors mix with what's beneath it — multiply, screen, overlay, and more. Applied per text layer, asset, or screenshot layer for compositing effects.",
  },
  {
    term: "Border radius",
    body: "The corner rounding of the screenshot (0–48px). Distinct from the canvas border radius, which rounds the outer canvas card (0–80px).",
  },
  {
    term: "Bulk edit",
    body: "A board view where multiple canvases live side by side on an infinite surface, so you can arrange, compare, and style several screenshots at once before exporting or previewing them.",
  },
  {
    term: "Canvas",
    body: "One styled screenshot card — the core unit of a Tokokino document. Each canvas holds its own screenshot, background, effects, layers, and framing. A project can hold up to 20.",
  },
  {
    term: "Custom preset",
    body: "A saved look — layout, styling, and framing bundled together — that you can re-apply across future shots and drafts so a polished treatment only has to be built once.",
  },
  {
    term: "Device frame",
    body: "A pixel-true mockup wrapper around your capture: iPhone, iPad, Galaxy, Pixel, MacBook, iMac, Apple Watch, or browser chrome such as Safari, Chrome, and Arc. Frames have a color and a vertical or horizontal orientation.",
  },
  {
    term: "Draft",
    body: "A saved, in-progress editor state stored to your account so you can leave and return to the same composition. Drafts keep the full state plus a thumbnail preview.",
  },
  {
    term: "Enhance preset",
    body: "A one-tap image treatment applied to the screenshot — Auto, Vivid, Soft, Dramatic, or Sharp — that adjusts brightness, contrast, and saturation without manual sliders.",
  },
  {
    term: "Export resolution",
    body: "The output width your image renders at: HD (1920px), 4K (3840px), or 8K (7680px). Resolution is separate from canvas zoom, which only affects your editing viewport.",
  },
  {
    term: "Keyframe",
    body: "A point on the timeline that captures target values — position, zoom, tilt, shadow, lighting, background, filters — so the editor can animate smoothly between states for a demo.",
  },
  {
    term: "Layer",
    body: "Any stackable element over the capture — text, image, SVG, or annotation. Layers carry a z-index that controls draw order, and can be brought forward or sent back.",
  },
  {
    term: "Layout preset",
    body: "A composition that arranges multiple screenshot slots — Side by Side, Depth Duo, Fan Out, Scatter, Perspective, and more — each defining per-slot position, rotation, tilt, and scale.",
  },
  {
    term: "Object fit",
    body: "How the screenshot sizes into its box: contain (fit whole image), cover (fill and crop), or fill (stretch to the box). Controls what happens when image and box proportions differ.",
  },
  {
    term: "Overlay",
    body: "A texture laid over or under the screenshot — one of 100 presets — with adjustable opacity, used to add grain, light leaks, or surface character.",
  },
  {
    term: "Padding",
    body: "The space (0–240px) between the screenshot and the edge of the canvas card, giving the capture room to breathe against the background.",
  },
  {
    term: "Portrait mode",
    body: "A depth-of-field effect — Soft, Studio, Spot, Frame, Iris, Blur, or Stage — that blurs around a focal region to draw the eye, tuned by intensity, position, and distance.",
  },
  {
    term: "Screenshot slot",
    body: "An extra capture card placed on a canvas beyond the primary screenshot — up to three per canvas. Slots power multi-shot layouts and each has its own position, tilt, scale, and filter.",
  },
  {
    term: "Shadow",
    body: "The cast shadow beneath the screenshot. Six types — Drop, Soft, Hard, Glow, Float, and Linear — each with adjustable intensity, light-source direction, and custom color.",
  },
  {
    term: "Share link",
    body: "A public URL for a captured composition. Tokokino renders the canvas to an image, uploads it, and returns a link anyone can open — with view tracking and per-user deduplication.",
  },
  {
    term: "Tilt",
    body: "A 3D rotation of the screenshot around the X, Y, and Z axes (each -180° to 180°), giving the capture perspective and depth. Often paired with scale via single-shot tilt presets.",
  },
  {
    term: "Timeline",
    body: "The animation track where keyframes live. Scrubbing the timeline plays the transitions between keyframes, which you can render out as a GIF or WebM product demo with optional audio.",
  },
  {
    term: "Watermark",
    body: "An optional mark stamped onto exports or animated renders to attribute the source, applied during the capture step rather than baked into the editable canvas.",
  },
  {
    term: "Zoom",
    body: "The magnification of the editing viewport (canvas zoom). It changes how large the canvas appears while you work and has no effect on export resolution or the final image.",
  },
]

type GlossaryGroup = {
  letter: string
  id: string
  terms: GlossaryTerm[]
}

const groups: GlossaryGroup[] = terms
  .slice()
  .sort((a, b) => a.term.localeCompare(b.term))
  .reduce<GlossaryGroup[]>((acc, entry) => {
    const letter = entry.term[0].toUpperCase()
    const existing = acc.find((group) => group.letter === letter)
    if (existing) {
      existing.terms.push(entry)
    } else {
      acc.push({ letter, id: `letter-${letter.toLowerCase()}`, terms: [entry] })
    }
    return acc
  }, [])

const indexItems = groups.map((group) => ({
  id: group.id,
  label: group.letter,
}))

export default function GlossaryPage() {
  return (
    <main
      className="relative isolate min-h-svh bg-background text-foreground"
      style={
        {
          "--rail": "color-mix(in oklch, var(--foreground) 20%, transparent)",
        } as CSSProperties
      }
    >
      <div className={CONTENT_WIDTH}>
        <Nav />
      </div>

      <section className="border-b border-border/70 bg-card/30">
        <div
          className={`flex w-full flex-col gap-10 px-5 py-7 sm:px-8 lg:px-12 ${CONTENT_WIDTH}`}
        >
          <Breadcrumb>
            <BreadcrumbList className="label-eyebrow gap-1.5 text-muted-foreground">
              <BreadcrumbItem>
                <BreadcrumbLink asChild className="hover:text-foreground">
                  <Link href="/">Home</Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage className="text-muted-foreground">
                  Glossary
                </BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>

          <div className="min-w-0 space-y-4 text-left">
            <h1 className="max-w-full text-[clamp(1.75rem,5.2vw,5.05rem)] leading-[0.95] font-semibold tracking-[-0.04em]">
              Glossary
            </h1>
            <p className="max-w-2xl text-sm leading-7 text-muted-foreground sm:text-base">
              The vocabulary of the Tokokino editor — every term you&rsquo;ll
              meet while styling a capture, from backdrops and device frames to
              keyframes, portrait modes, and export resolutions.
            </p>
            <p className="text-sm leading-7 text-muted-foreground">
              <strong className="font-semibold text-foreground">
                {terms.length}
              </strong>{" "}
              terms across{" "}
              <strong className="font-semibold text-foreground">
                {groups.length}
              </strong>{" "}
              sections.
            </p>
          </div>
        </div>
      </section>

      <section
        className={`grid w-full gap-10 px-5 py-10 sm:px-8 lg:grid-cols-[240px_1fr] lg:px-12 lg:py-14 ${CONTENT_WIDTH}`}
      >
        <aside className="hidden lg:block">
          <GlossaryIndex items={indexItems} />
        </aside>

        <article className="min-w-0 space-y-9">
          <div className="border-l-2 border-primary/60 pl-5 text-sm leading-7 text-muted-foreground">
            <p>
              Terms are grouped alphabetically. Jump straight to a letter from
              the index, or scroll through to build a mental model of how the
              editor fits together.
            </p>
          </div>

          {groups.map((group) => (
            <section
              key={group.id}
              id={group.id}
              className="scroll-mt-8 border-t border-border/70 pt-8"
            >
              <h2 className="flex items-baseline gap-3 text-xl font-semibold tracking-[-0.02em]">
                <span className="text-primary tabular-nums">
                  {group.letter}
                </span>
                <span className="text-xs font-medium text-muted-foreground">
                  {group.terms.length}{" "}
                  {group.terms.length === 1 ? "term" : "terms"}
                </span>
              </h2>
              <dl className="mt-5 space-y-6">
                {group.terms.map((entry) => (
                  <div
                    key={entry.term}
                    id={slugify(entry.term)}
                    className="scroll-mt-8"
                  >
                    <dt className="text-base font-medium tracking-[-0.01em] text-foreground">
                      {entry.term}
                    </dt>
                    <dd className="mt-1.5 max-w-2xl text-sm leading-7 text-muted-foreground">
                      {entry.body}
                    </dd>
                  </div>
                ))}
              </dl>
            </section>
          ))}
        </article>
      </section>

      <div className={CONTENT_WIDTH}>
        <Footer showRail={false} />
      </div>
      <ScrollToTop />
    </main>
  )
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}
