import type { Metadata } from "next"
import Link from "next/link"
import type { CSSProperties, ReactNode } from "react"

import { Footer } from "@/components/landing/footer"
import { Nav } from "@/components/landing/nav"
import { ScrollToTop } from "@/components/landing/scroll-to-top"
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"

import { GlossaryIndex } from "./glossary-index"

const CONTENT_WIDTH =
  "mx-auto max-w-[76rem] w-[calc(100%-1rem)] sm:w-[calc(100%-2rem)] md:w-[calc(100%-3rem)] lg:w-[calc(100%-4rem)] xl:w-full"

export const metadata: Metadata = {
  title: "Glossary — Tokokino",
  description:
    "Definitions for every term in the Tokokino editor — from backdrops and device frames to keyframes, portrait modes, and export resolutions.",
}

type GlossaryTerm = {
  term: string
  body: ReactNode
}

const terms: GlossaryTerm[] = [
  {
    term: "Animate mode",
    body: "The editing mode that swaps the inspector for a timeline, letting you build a motion sequence from the same canvas you styled — then render it out as a video or GIF.",
  },
  {
    term: "Annotation",
    body: "A mark drawn directly over your capture — arrows, shapes, or freehand strokes. Annotations sit on their own layer so you can point at what matters without touching the underlying screenshot.",
  },
  {
    term: "Aspect ratio",
    body: "The width-to-height proportion of the canvas — 16:9, 1:1, 4:3, 9:16, or a custom ratio. Aspect ratio shapes the frame you export into and is independent of the resolution you export at.",
  },
  {
    term: "Asset",
    body: "An image or SVG layered on top of the canvas — a logo, badge, or decorative element. Each asset carries its own position, rotation, z-index, opacity, blend mode, and filter.",
  },
  {
    term: "Auto palette",
    body: "A background generated by sampling the dominant colors from your screenshot, producing a gradient that belongs to the capture instead of clashing with it.",
  },
  {
    term: "Backdrop",
    body: "The layer behind the screenshot but inside the padding. It carries effects (noise, blur, brightness), an optional pattern, and its own filter — the atmosphere your capture sits against.",
  },
  {
    term: "Background",
    body: "The fill behind everything on the canvas. It can be none, a solid color, a gradient, an uploaded image, or an auto-sampled palette drawn from your screenshot.",
  },
  {
    term: "Blend mode",
    body: "How a layer's colors mix with what's beneath it — multiply, screen, overlay, and more. Applied per text layer, asset, or screenshot layer for compositing effects.",
  },
  {
    term: "Border",
    body: "An outline drawn around the screenshot, with its own color, width (0–12px), style, and inner padding (0–80px) — useful for lifting a light capture off a light background.",
  },
  {
    term: "Border radius",
    body: "The corner rounding of the screenshot (0–48px). Distinct from the canvas border radius, which rounds the outer canvas card (0–80px).",
  },
  {
    term: "Bulk edit",
    body: "A board view where multiple canvases live side by side on an infinite surface, so you can arrange, compare, and style several screenshots at once before exporting or previewing them.",
  },
  {
    term: "Canvas",
    body: "One styled screenshot card — the core unit of a Tokokino document. Each canvas holds its own screenshot, background, effects, layers, and framing. A project can hold up to 20.",
  },
  {
    term: "Clip",
    body: "The unit of animation on the timeline — a span with a start, a duration, and a set of effects it owns. Playback eases each effect from the committed baseline toward the clip's target values.",
  },
  {
    term: "Color grade",
    body: "Per-pixel adjustments applied to the screenshot or video itself — blur, brightness, contrast, saturation, hue, grayscale, sepia, and invert. Distinct from the backdrop's grade, which affects only the layer behind.",
  },
  {
    term: "Crop",
    body: "Trimming the capture down to a region of interest. Tokokino keeps the original untouched behind the crop, so you can re-crop or restore the full frame at any point.",
  },
  {
    term: "Custom preset",
    body: "A saved look — layout, styling, and framing bundled together — that you can re-apply across future shots and drafts so a polished treatment only has to be built once.",
  },
  {
    term: "Device frame",
    body: "A pixel-true mockup wrapper around your capture: iPhone, iPad, Galaxy, Pixel, MacBook, iMac, Apple Watch, or browser chrome such as Safari, Chrome, and Arc. Frames have a color and a vertical or horizontal orientation.",
  },
  {
    term: "Draft",
    body: "A saved, in-progress editor state stored to your account so you can leave and return to the same composition. Drafts keep the full state plus a thumbnail preview.",
  },
  {
    term: "Easing",
    body: "The curve a clip follows between its baseline and its target — linear, cubic, ease-in, ease-out, ease-in-out, out-circ, or a custom cubic-bezier you drag by hand. Easing is what separates mechanical motion from motion that feels designed.",
  },
  {
    term: "Enhance preset",
    body: "A one-tap image treatment applied to the screenshot — Auto, Vivid, Soft, Dramatic, or Sharp — that adjusts brightness, contrast, and saturation without manual sliders.",
  },
  {
    term: "Export resolution",
    body: "The output width your image renders at: HD (1920px), 4K (3840px), or 8K (7680px). Resolution is separate from canvas zoom, which only affects your editing viewport.",
  },
  {
    term: "Filter",
    body: "A named look applied to a screenshot, video, or asset layer — B&W, Sepia, Vintage, Warm, Cool, Fade, Vivid, Noir, Dream, Mono, or Invert. Filters stack on top of any manual color grade.",
  },
  {
    term: "Keyframe",
    body: "A point on the timeline that captures target values — position, zoom, tilt, shadow, lighting, background, filters — so the editor can animate smoothly between states for a demo. In Tokokino a keyframe is expressed as a clip.",
  },
  {
    term: "Layer",
    body: "Any stackable element over the capture — text, image, SVG, or annotation. Layers carry a z-index that controls draw order, and can be brought forward or sent back.",
  },
  {
    term: "Layout preset",
    body: "A composition that arranges multiple screenshot slots — Side by Side, Depth Duo, Fan Out, Scatter, Perspective, and more — each defining per-slot position, rotation, tilt, and scale.",
  },
  {
    term: "Object fit",
    body: "How the screenshot sizes into its box: contain (fit whole image), cover (fill and crop), or fill (stretch to the box). Controls what happens when image and box proportions differ.",
  },
  {
    term: "Offline editing",
    body: "The editor keeps working with no network. Drafts persist locally and sync back to your account once you reconnect — only sharing and cloud capture need a connection.",
  },
  {
    term: "Overlay",
    body: "A texture laid over or under the screenshot — one of 100 presets — with adjustable opacity, used to add grain, light leaks, or surface character.",
  },
  {
    term: "Padding",
    body: "The space (0–240px) between the screenshot and the edge of the canvas card, giving the capture room to breathe against the background.",
  },
  {
    term: "Pattern",
    body: "A repeating geometric texture drawn into the backdrop — grids, dots, lines, and more — with adjustable intensity, stroke thickness, and color.",
  },
  {
    term: "Portrait mode",
    body: "A depth-of-field effect — Soft, Studio, Spot, Frame, Iris, Blur, or Stage — that blurs around a focal region to draw the eye, tuned by intensity, position, and distance.",
  },
  {
    term: "Preview mode",
    body: "A distraction-free playback of your canvases in sequence, with slide, fade, zoom, or flip transitions and optional auto-scroll — a way to review a set before exporting it.",
  },
  {
    term: "Scale",
    body: "The size of the screenshot inside its canvas, from 10% to 300%. Scale changes the capture within the frame; it does not change the canvas or the exported resolution.",
  },
  {
    term: "Screenshot placement",
    body: "Where the capture sits inside the canvas — snapped to a point on a 5×5 grid or centered, then nudged by a pixel offset for fine positioning.",
  },
  {
    term: "Screenshot slot",
    body: "An extra capture card placed on a canvas beyond the primary screenshot — up to three per canvas. Slots power multi-shot layouts and each has its own position, tilt, scale, and filter.",
  },
  {
    term: "Shadow",
    body: "The cast shadow beneath the screenshot. Six types — Drop, Soft, Hard, Glow, Float, and Linear — each with adjustable intensity, light-source direction, and custom color.",
  },
  {
    term: "Shape",
    body: "One of 106 rendered 3D objects you can drop onto a canvas. A shape becomes an ordinary asset layer, so it moves, scales, filters, and reorders like any other image.",
  },
  {
    term: "Share link",
    body: "A public URL for a captured composition — still or animated. Tokokino renders the canvas, uploads it, and returns a link anyone can open, with view tracking and per-user deduplication.",
  },
  {
    term: "Social post mockup",
    body: "An X or Bluesky post rendered as a card on the canvas in place of a screenshot. Paste a post URL and Tokokino rebuilds it, so you can style it like any other capture.",
  },
  {
    term: "Template",
    body: "One of 20 ready-made compositions — background, framing, layers, and in several cases a full animation — applied to a canvas in one click as a starting point rather than a locked result.",
  },
  {
    term: "Text layer",
    body: "Free-floating type placed over the canvas, with its own font, weight, size, spacing, color, stroke, shadow, alignment, opacity, and blend mode. Over 100 Google Fonts are available.",
  },
  {
    term: "Tilt",
    body: "A 3D rotation of the screenshot around the X, Y, and Z axes (each -180° to 180°), giving the capture perspective and depth. Often paired with scale via single-shot tilt presets.",
  },
  {
    term: "Timeline",
    body: "The per-canvas animation track where clips live. Scrubbing the timeline plays the transitions between them, which you can render out as a WebM, MP4, or GIF product demo with optional audio.",
  },
  {
    term: "Trim",
    body: "Cutting a video down to the segment you want, and muting it if you don't want the audio. Trimmed segments map onto the animation timeline so motion and footage stay in sync.",
  },
  {
    term: "Undo history",
    body: "The stack of document states behind every edit — up to 100 steps back. Styling, layers, and layout changes are undoable; view state such as zoom and mode is not.",
  },
  {
    term: "URL capture",
    body: "Screenshotting a live webpage by pasting its address. Tokokino loads the page in a headless browser and returns the capture, optionally as a full-page shot you can scroll within the frame.",
  },
  {
    term: "Video export",
    body: "Encoding an animated canvas to WebM, MP4, or GIF. The entire encode runs on your device — frames are captured, muxed with any source audio, and written out without the footage leaving your machine.",
  },
  {
    term: "Watermark",
    body: "An optional mark stamped onto exports or animated renders to attribute the source, applied during the capture step rather than baked into the editable canvas.",
  },
  {
    term: "Zoom",
    body: "The magnification of the editing viewport (canvas zoom). It changes how large the canvas appears while you work and has no effect on export resolution or the final image.",
  },
]

type GlossaryGroup = {
  letter: string
  id: string
  terms: GlossaryTerm[]
}

const groups: GlossaryGroup[] = terms
  .slice()
  .sort((a, b) => a.term.localeCompare(b.term))
  .reduce<GlossaryGroup[]>((acc, entry) => {
    const letter = entry.term[0].toUpperCase()
    const existing = acc.find((group) => group.letter === letter)
    if (existing) {
      existing.terms.push(entry)
    } else {
      acc.push({ letter, id: `letter-${letter.toLowerCase()}`, terms: [entry] })
    }
    return acc
  }, [])

const indexItems = groups.map((group) => ({
  id: group.id,
  label: group.letter,
}))

export default function GlossaryPage() {
  return (
    <main
      className="relative isolate min-h-svh bg-background text-foreground"
      style={
        {
          "--rail": "color-mix(in oklch, var(--foreground) 20%, transparent)",
        } as CSSProperties
      }
    >
      <div className={CONTENT_WIDTH}>
        <Nav />
      </div>

      <section className="border-b border-border/70 bg-card/30">
        <div
          className={`flex w-full flex-col gap-10 px-5 py-7 sm:px-8 lg:px-12 ${CONTENT_WIDTH}`}
        >
          <Breadcrumb>
            <BreadcrumbList className="label-eyebrow gap-1.5 text-muted-foreground">
              <BreadcrumbItem>
                <BreadcrumbLink asChild className="hover:text-foreground">
                  <Link href="/">Home</Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage className="text-muted-foreground">
                  Glossary
                </BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>

          <div className="min-w-0 space-y-4 text-left">
            <h1 className="max-w-full text-[clamp(1.75rem,5.2vw,5.05rem)] leading-[0.95] font-semibold tracking-[-0.04em]">
              Glossary
            </h1>
            <p className="max-w-2xl text-sm leading-7 text-muted-foreground sm:text-base">
              The vocabulary of the Tokokino editor — every term you&rsquo;ll
              meet while styling a capture, from backdrops and device frames to
              keyframes, portrait modes, and export resolutions.
            </p>
            <p className="text-sm leading-7 text-muted-foreground">
              <strong className="font-semibold text-foreground">
                {terms.length}
              </strong>{" "}
              terms across{" "}
              <strong className="font-semibold text-foreground">
                {groups.length}
              </strong>{" "}
              sections.
            </p>
          </div>
        </div>
      </section>

      <section
        className={`grid w-full gap-10 px-5 py-10 sm:px-8 lg:grid-cols-[240px_1fr] lg:px-12 lg:py-14 ${CONTENT_WIDTH}`}
      >
        <aside className="hidden lg:block">
          <GlossaryIndex items={indexItems} />
        </aside>

        <article className="min-w-0 space-y-9">
          <div className="border-l-2 border-primary/60 pl-5 text-sm leading-7 text-muted-foreground">
            <p>
              Terms are grouped alphabetically. Jump straight to a letter from
              the index, or scroll through to build a mental model of how the
              editor fits together.
            </p>
          </div>

          {groups.map((group) => (
            <section
              key={group.id}
              id={group.id}
              className="scroll-mt-8 border-t border-border/70 pt-8"
            >
              <h2 className="flex items-baseline gap-3 text-xl font-semibold tracking-[-0.02em]">
                <span className="text-primary tabular-nums">
                  {group.letter}
                </span>
                <span className="text-xs font-medium text-muted-foreground">
                  {group.terms.length}{" "}
                  {group.terms.length === 1 ? "term" : "terms"}
                </span>
              </h2>
              <dl className="mt-5 space-y-6">
                {group.terms.map((entry) => (
                  <div
                    key={entry.term}
                    id={slugify(entry.term)}
                    className="scroll-mt-8"
                  >
                    <dt className="text-base font-medium tracking-[-0.01em] text-foreground">
                      {entry.term}
                    </dt>
                    <dd className="mt-1.5 max-w-2xl text-sm leading-7 text-muted-foreground">
                      {entry.body}
                    </dd>
                  </div>
                ))}
              </dl>
            </section>
          ))}
        </article>
      </section>

      <div className={CONTENT_WIDTH}>
        <Footer showRail={false} />
      </div>
      <ScrollToTop />
    </main>
  )
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}
