import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { basename, dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const guidesDir = join(root, "content", "guides")
const outFile = join(root, "lib", "guides", "sources.ts")

const entries = readdirSync(guidesDir)
  .filter((file) => file.endsWith(".md"))
  .sort()
  .map((file) => [basename(file, ".md"), readFileSync(join(guidesDir, file), "utf8")])

const body = entries
  .map(([slug, source]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(source)},`)
  .join("\n")

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  `// Generated by scripts/build-guides.mjs from content/guides/*.md — do not edit.\n\nexport const GUIDE_SOURCES: Record<string, string> = {\n${body}\n}\n`,
)

console.log(`build-guides: wrote ${entries.length} guide${entries.length === 1 ? "" : "s"} to lib/guides/sources.ts`)
