import type { Template } from "./types"
import { templateMeta } from "./catalog"

const threeDTilt: Template = {
  ...templateMeta["3d-tilt"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: { id: "auto", w: 0, h: 0 },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "image",
            value:
              "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
            sourceUrl:
              "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
            thumbUrl:
              "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=400",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: { color: null, width: 1, style: "solid", padding: 0 },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 50,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: { rx: 0, ry: 11, rz: 0 },
          scale: 100,
          screenshotPosition: "2-4",
          screenshotOffset: { x: 57.06228462837828, y: 0 },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 8,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "none",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: { id: null, opacity: 50, position: "overlay" },
          frame: { id: "none", color: "black", orientation: "vertical" },
          portrait: { mode: "off", intensity: 60, position: 50, distance: 50 },
          texts: [],
          assets: [],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [],
          frameAddress: "",
          tweet: null,
          animation: {
            durationMs: 10100,
            clips: [
              {
                id: "3a29dbbc-87c6-43f6-8f96-26eba02aa5d0",
                startMs: 0,
                durationMs: 3279.248046875,
                target: { scope: "all" },
                pose: {
                  tilt: { rx: 10, ry: -13, rz: 0 },
                  scale: 76,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 90,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["zoom", "tilt"],
                easing: "linear",
                returnToDefault: false,
              },
              {
                id: "a200a0c1-9fe9-4358-93a8-9509e45f42d4",
                startMs: 3279.248046875,
                durationMs: 3097.0703125,
                target: { scope: "all" },
                pose: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 10, ry: -13, rz: 0 },
                  scale: 86,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["zoom", "tilt"],
                returnToDefault: false,
              },
              {
                id: "79c78e4b-04e5-44e8-b1b8-25fda78df9e9",
                startMs: 6376.318359375,
                durationMs: 3595.41015625,
                target: { scope: "all" },
                pose: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1635771629306-788f8c965a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0N3x8d2hpdGUlMjBiYWNrZ3JvdW5kJTIwd2l0aCUyMGJsYWNrJTIwYmFsbHN8ZW58MXwwfHx8MTc4NDkxMjIwOHww&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["tilt", "position", "lighting"],
              },
            ],
          },
          id: "canvas-default",
          position: { x: 0, y: 0 },
          fullPageCapture: { scrollPosition: 0 },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: true,
    },
  },
}

export default threeDTilt
