import type { Template } from "./types"
import { templateMeta } from "./catalog"

const asciiCascade: Template = {
  ...templateMeta["ascii-cascade"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: { id: "auto", w: 0, h: 0 },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "image",
            value:
              "https://assets.tokokino.com/Backgrounds/Fluid/solen-feyissa-5nzyshozhx4-unsplash.jpg",
            sourceUrl:
              "https://assets.tokokino.com/Backgrounds/Fluid/solen-feyissa-5nzyshozhx4-unsplash.jpg",
            thumbUrl:
              "https://assets.tokokino.com/Backgrounds/Fluid/thumbs/solen-feyissa-5nzyshozhx4-unsplash.webp",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: { color: null, width: 1, style: "solid", padding: 0 },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 0,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
            ascii: {
              enabled: true,
              resolution: 136,
              charset: "blocks",
              colored: true,
              inverted: true,
              color: "#FFFFFF",
              opacity: 100,
            },
          },
          tilt: { rx: 0, ry: 0, rz: 0 },
          scale: 100,
          screenshotPosition: "center",
          screenshotOffset: { x: 0, y: 0 },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 3,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "none",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: { id: null, opacity: 50, position: "overlay" },
          frame: {
            id: "glass-stack",
            color: "dark",
            orientation: "horizontal",
          },
          portrait: { mode: "off", intensity: 60, position: 50, distance: 50 },
          texts: [],
          assets: [],
          enhance: "off",
          mediaAdjustments: {
            blur: 0,
            brightness: 100,
            contrast: 100,
            saturation: 100,
            hue: 0,
            grayscale: 0,
            sepia: 0,
            invert: 0,
          },
          mediaFilter: "none",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [],
          frameAddress: "",
          tweet: null,
          animation: { durationMs: 5000, clips: [] },
          id: "canvas-default",
          position: { x: 0, y: 0 },
          fullPageCapture: { scrollPosition: 0 },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: false,
    },
  },
}

export default asciiCascade
