import type { Template } from "./types"
import { templateMeta } from "./catalog"

const iphoneSpotlight: Template = {
  ...templateMeta["iphone-spotlight"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: { id: "auto", w: 0, h: 0 },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "solid",
            value: "#ffffff",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: {
            color: null,
            width: 1,
            style: "solid",
            padding: 0,
          },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 0,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: { rx: 0, ry: 0, rz: -11 },
          scale: 85,
          screenshotPosition: "center",
          screenshotOffset: {
            x: 62.851474521396426,
            y: -81.73740146396396,
          },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 1,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "hard",
            intensity: 43,
            lightSource: "0.03-0.21",
            color: "#050505",
          },
          overlay: { id: 2, opacity: 40, position: "overlay" },
          frame: { id: "iphone_17", color: "black", orientation: "vertical" },
          portrait: {
            mode: "off",
            intensity: 60,
            position: 50,
            distance: 50,
          },
          texts: [],
          assets: [],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [
            {
              id: "10147e36-6b8d-42dc-abad-42911c6acc3f",
              src: null,
              originalSrc: null,
              lastCropRegion: null,
              fullPageCapture: null,
              xPct: 61.73892321887316,
              yPct: 61.19510135135135,
              widthPct: 48.00000000000001,
              heightPct: 28,
              rotation: 13,
              tilt: { rx: 0, ry: 0, rz: 0 },
              scale: 85,
              zIndex: 2,
              filter: "none",
              objectFit: "contain",
              border: { color: null, width: 1, style: "solid", padding: 0 },
              borderRadius: 7,
              padding: 40,
              shadow: {
                type: "hard",
                intensity: 43,
                lightSource: "0.03-0.21",
                color: "#050505",
              },
              lighting: {
                target: "inner",
                intensity: 0,
                direction: "0-0",
                color: "#FFFFFF",
              },
              frame: {
                id: "iphone_17",
                color: "black",
                orientation: "vertical",
              },
            },
          ],
          frameAddress: "",
          tweet: null,
          animation: { durationMs: 5000, clips: [] },
          id: "canvas-default",
          position: { x: 0, y: 0 },
          fullPageCapture: { scrollPosition: 0 },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: false,
    },
  },
}

export default iphoneSpotlight
