import type { Template } from "./types"
import { templateMeta } from "./catalog"

const productReveal: Template = {
  ...templateMeta["product-reveal"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: {
        id: "auto",
        w: 0,
        h: 0,
      },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "auto",
            value: "linear-gradient(45deg, #0c0e0f, #2c2d2e)",
            sourceUrl:
              "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
            thumbUrl:
              "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 16,
          border: {
            color: "rgba(15,15,20,0.55)",
            width: 8,
            style: "solid",
            padding: 3,
          },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 7,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: {
            rx: 0,
            ry: 0,
            rz: 0,
          },
          scale: 100,
          screenshotPosition: "center",
          screenshotOffset: {
            x: 0,
            y: 0,
          },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 13,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "glow",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: {
            id: 2,
            opacity: 26,
            position: "underlay",
          },
          frame: {
            id: "none",
            color: "black",
            orientation: "vertical",
          },
          portrait: {
            mode: "off",
            intensity: 60,
            position: 22,
            distance: 74,
          },
          texts: [],
          assets: [],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [],
          frameAddress: "",
          tweet: null,
          animation: {
            durationMs: 10400,
            clips: [
              {
                id: "541a6a37-9adf-4908-936b-d84e84fd6f1c",
                startMs: 0,
                durationMs: 5732.861328125,
                target: {
                  scope: "all",
                },
                pose: {
                  tilt: {
                    rx: 45,
                    ry: 0,
                    rz: 0,
                  },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: {
                    x: 0,
                    y: 0,
                  },
                  padding: 40,
                  canvasBorderRadius: 16,
                  shadow: {
                    type: "glow",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 7,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value: "linear-gradient(45deg, #0c0e0f, #2c2d2e)",
                    sourceUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
                    thumbUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 22,
                    distance: 74,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: {
                    id: 2,
                    opacity: 26,
                    position: "underlay",
                  },
                  border: {
                    color: "rgba(15,15,20,0.55)",
                    width: 8,
                    style: "solid",
                    padding: 3,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: {
                    rx: 45,
                    ry: 0,
                    rz: -44,
                  },
                  scale: 116,
                  screenshotPosition: "4-4",
                  screenshotOffset: {
                    x: 56.71699290540539,
                    y: 140.7008399493243,
                  },
                  padding: 40,
                  canvasBorderRadius: 16,
                  shadow: {
                    type: "glow",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value: "linear-gradient(45deg, #0c0e0f, #2c2d2e)",
                    sourceUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
                    thumbUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 22,
                    distance: 74,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: {
                    id: 63,
                    opacity: 26,
                    position: "underlay",
                  },
                  border: {
                    color: "rgba(15,15,20,0.55)",
                    width: 8,
                    style: "solid",
                    padding: 3,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["tilt", "lighting", "overlay"],
                returnToDefault: false,
                easing: "inOut",
              },
              {
                id: "533cab82-d7ae-4a25-93d9-fda46d5bf40c",
                startMs: 5732.861328125,
                durationMs: 4598.92578125,
                target: {
                  scope: "all",
                },
                pose: {
                  tilt: {
                    rx: 0,
                    ry: 0,
                    rz: 0,
                  },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: {
                    x: 0,
                    y: 0,
                  },
                  padding: 40,
                  canvasBorderRadius: 16,
                  shadow: {
                    type: "glow",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 7,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value: "linear-gradient(45deg, #0c0e0f, #2c2d2e)",
                    sourceUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
                    thumbUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 22,
                    distance: 74,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: {
                    id: null,
                    opacity: 26,
                    position: "underlay",
                  },
                  border: {
                    color: "rgba(15,15,20,0.55)",
                    width: 8,
                    style: "solid",
                    padding: 3,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: {
                    rx: 45,
                    ry: 0,
                    rz: 0,
                  },
                  scale: 116,
                  screenshotPosition: "center",
                  screenshotOffset: {
                    x: 0,
                    y: 0,
                  },
                  padding: 40,
                  canvasBorderRadius: 16,
                  shadow: {
                    type: "glow",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value: "linear-gradient(45deg, #0c0e0f, #2c2d2e)",
                    sourceUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
                    thumbUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 22,
                    distance: 74,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: {
                    id: 63,
                    opacity: 26,
                    position: "underlay",
                  },
                  border: {
                    color: "rgba(15,15,20,0.55)",
                    width: 8,
                    style: "solid",
                    padding: 3,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["tilt", "zoom", "lighting"],
                returnToDefault: false,
                easing: "out",
              },
            ],
          },
          id: "canvas-default",
          position: {
            x: 0,
            y: 0,
          },
          fullPageCapture: {
            scrollPosition: 0,
          },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: true,
    },
  },
}

export default productReveal
