import type { Template } from "./types"
import { templateMeta } from "./catalog"

const shapeReveal: Template = {
  ...templateMeta["shape-reveal"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: { id: "auto", w: 0, h: 0 },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "auto",
            value:
              "linear-gradient(183deg, #fdfefe, #0b3694, #0b3694, #0b3694)",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: {
            color: "rgba(255,255,255,0.5)",
            width: 6,
            style: "solid",
            padding: 0,
          },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 0,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: { rx: 0, ry: 0, rz: 0 },
          scale: 100,
          screenshotPosition: "center",
          screenshotOffset: { x: 0, y: 0 },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 5,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "none",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: { id: null, opacity: 50, position: "overlay" },
          frame: { id: "none", color: "black", orientation: "vertical" },
          portrait: { mode: "off", intensity: 60, position: 50, distance: 50 },
          texts: [],
          assets: [
            {
              id: "b5f2fed4-4970-4028-bb6b-6616e464328d",
              src: "https://assets.tokokino.com/Shapes/holo-48.webp",
              xPct: 4.904147311373872,
              yPct: 12.168144707207201,
              widthPct: 30.607316300675677,
              heightPct: 48.97170608108108,
              rotation: 0,
              zIndex: 2,
              opacity: 100,
              filter: "none",
              blendMode: "normal",
              hidden: false,
              flipX: true,
              flipY: false,
            },
            {
              id: "a7a4a95f-df77-43f0-ab0c-a1f41efbbd83",
              src: "https://assets.tokokino.com/Shapes/holo-48.webp",
              xPct: 94.08019249718468,
              yPct: 10.804969031531524,
              widthPct: 30.607316300675677,
              heightPct: 48.97170608108108,
              rotation: 0,
              zIndex: 1,
              opacity: 100,
              filter: "none",
              blendMode: "normal",
              hidden: false,
              flipX: false,
              flipY: false,
            },
            {
              id: "221a95ea-14c5-4ae8-accd-bf0904920aff",
              src: "https://assets.tokokino.com/Shapes/holo-48.webp",
              xPct: 93.91434403153153,
              yPct: 91.74120213963963,
              widthPct: 30.607316300675677,
              heightPct: 48.97170608108108,
              rotation: 0,
              zIndex: 3,
              opacity: 100,
              filter: "none",
              blendMode: "normal",
              hidden: false,
              flipX: false,
              flipY: true,
            },
            {
              id: "35a67228-2a49-4874-9b36-2a46be36e310",
              src: "https://assets.tokokino.com/Shapes/holo-48.webp",
              xPct: 7.155123873873865,
              yPct: 91.73001126126127,
              widthPct: 30.607316300675677,
              heightPct: 48.97170608108108,
              rotation: 0,
              zIndex: 4,
              opacity: 100,
              filter: "none",
              blendMode: "normal",
              hidden: false,
              flipX: true,
              flipY: true,
            },
          ],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [],
          frameAddress: "",
          tweet: null,
          animation: {
            durationMs: 10300,
            clips: [
              {
                id: "ad7f6a3f-bb21-47f4-98fb-990a38842c1a",
                startMs: 1319.7265625,
                durationMs: 4775,
                target: { scope: "main" },
                pose: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value:
                      "linear-gradient(183deg, #fdfefe, #0b3694, #0b3694, #0b3694)",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: {
                    color: "rgba(255,255,255,0.5)",
                    width: 6,
                    style: "solid",
                    padding: 0,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 85,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value:
                      "linear-gradient(183deg, #fdfefe, #0b3694, #0b3694, #0b3694)",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: {
                    color: null,
                    width: 1,
                    style: "solid",
                    padding: 0,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["zoom"],
                speed: 1.9513690232938292,
                returnToDefault: false,
              },
            ],
          },
          id: "canvas-default",
          position: { x: 0, y: 0 },
          fullPageCapture: { scrollPosition: 0 },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: true,
    },
  },
}

export default shapeReveal
