import type { Template } from "./types"
import { templateMeta } from "./catalog"

const slideReveal: Template = {
  ...templateMeta["slide-reveal"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: {
        id: "auto",
        w: 0,
        h: 0,
      },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "solid",
            value: "#ffffff",
            sourceUrl:
              "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
            thumbUrl:
              "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: {
            color: "#B3B5B9",
            width: 4,
            style: "solid",
            padding: 0,
          },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 0,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: {
            rx: 0,
            ry: 0,
            rz: 0,
          },
          scale: 100,
          screenshotPosition: "2-0",
          screenshotOffset: {
            x: -178.2989998592342,
            y: 0,
          },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 21,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "glow",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: {
            id: 23,
            opacity: 26,
            position: "overlay",
          },
          frame: {
            id: "none",
            color: "black",
            orientation: "vertical",
          },
          portrait: {
            mode: "off",
            intensity: 60,
            position: 50,
            distance: 50,
          },
          texts: [],
          assets: [],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [],
          frameAddress: "",
          tweet: null,
          animation: {
            durationMs: 10200,
            clips: [
              {
                id: "1d01abe7-b0be-455b-9203-94857fd820d2",
                startMs: 0,
                durationMs: 10197.16796875,
                target: {
                  scope: "main",
                },
                pose: {
                  tilt: {
                    rx: 0,
                    ry: 0,
                    rz: 0,
                  },
                  scale: 100,
                  screenshotPosition: "2-0",
                  screenshotOffset: {
                    x: -178.2989998592342,
                    y: 0,
                  },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "glow",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "solid",
                    value: "#ffffff",
                    sourceUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
                    thumbUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: {
                    id: 23,
                    opacity: 26,
                    position: "overlay",
                  },
                  border: {
                    color: "#B3B5B9",
                    width: 4,
                    style: "solid",
                    padding: 0,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: {
                    rx: 0,
                    ry: 0,
                    rz: 0,
                  },
                  scale: 100,
                  screenshotPosition: "2-4",
                  screenshotOffset: {
                    x: 242.61663780968456,
                    y: 0,
                  },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "glow",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "solid",
                    value: "#ffffff",
                    sourceUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/astra.webp",
                    thumbUrl:
                      "https://assets.tokokino.com/Backgrounds/Mesh/thumbs/astra.webp",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: {
                    id: 23,
                    opacity: 26,
                    position: "overlay",
                  },
                  border: {
                    color: "#B3B5B9",
                    width: 4,
                    style: "solid",
                    padding: 0,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["position"],
              },
            ],
          },
          id: "canvas-default",
          position: {
            x: 0,
            y: 0,
          },
          fullPageCapture: {
            scrollPosition: 0,
          },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: true,
    },
  },
}

export default slideReveal
