import type { Template } from "./types"

const twinPhoneStage: Template = {
  id: "twin-phones-stage",
  name: "Twin Phones, Stage",
  category: "image",
  thumbnail: "https://assets.tokokino.com/templates/twin-phones-stage.jpg",
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: {
        id: "auto",
        w: 0,
        h: 0,
      },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "auto",
            value: "linear-gradient(0deg, #10100e, #f4f4f4)",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: {
            color: null,
            width: 1,
            style: "solid",
            padding: 0,
          },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 0,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: {
            rx: 0,
            ry: 0,
            rz: 0,
          },
          scale: 85,
          screenshotPosition: "center",
          screenshotOffset: {
            x: 43.5106981981982,
            y: -56.894883164414416,
          },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 1,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "none",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: {
            id: 66,
            opacity: 50,
            position: "underlay",
          },
          frame: {
            id: "iphone_17_pro",
            color: "deep_blue",
            orientation: "vertical",
          },
          portrait: {
            mode: "off",
            intensity: 60,
            position: 50,
            distance: 50,
          },
          texts: [],
          assets: [],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [
            {
              id: "fedf344c-79e2-4cf5-a9f6-c6200c0c4aed",
              src: null,
              originalSrc: null,
              lastCropRegion: null,
              fullPageCapture: null,
              xPct: 56.25219946509007,
              yPct: 59.640343468468465,
              widthPct: 28.125,
              heightPct: 28,
              rotation: 0,
              tilt: {
                rx: 0,
                ry: 0,
                rz: 0,
              },
              scale: 85,
              zIndex: 2,
              filter: "none",
              objectFit: "contain",
              border: {
                color: null,
                width: 1,
                style: "solid",
                padding: 0,
              },
              borderRadius: 7,
              padding: 40,
              shadow: {
                type: "none",
                intensity: 40,
                lightSource: "center",
                color: "#050505",
              },
              lighting: {
                target: "inner",
                intensity: 0,
                direction: "0-0",
                color: "#FFFFFF",
              },
            },
          ],
          frameAddress: "",
          tweet: null,
          animation: {
            durationMs: 5000,
            clips: [],
          },
          id: "canvas-default",
          position: {
            x: 0,
            y: 0,
          },
          fullPageCapture: {
            scrollPosition: 0,
          },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: false,
    },
  },
}

export default twinPhoneStage
