import type { Template } from "./types"
import { templateMeta } from "./catalog"

const uiShowcaseAnimated: Template = {
  ...templateMeta["ui-showcase-animated"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: { id: "auto", w: 0, h: 0 },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "image",
            value:
              "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
            sourceUrl:
              "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
            thumbUrl:
              "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=400",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: { color: null, width: 1, style: "solid", padding: 0 },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 0,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: { rx: 0, ry: 0, rz: 0 },
          scale: 100,
          screenshotPosition: "center",
          screenshotOffset: { x: 0, y: 0 },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 2,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "none",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: { id: null, opacity: 50, position: "overlay" },
          frame: { id: "iphone_17", color: "black", orientation: "vertical" },
          portrait: { mode: "off", intensity: 60, position: 50, distance: 50 },
          texts: [],
          assets: [],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [],
          frameAddress: "",
          tweet: null,
          animation: {
            durationMs: 10200,
            clips: [
              {
                id: "95378232-7ffb-41b4-b054-63b1cbbcfd03",
                startMs: 0,
                durationMs: 1433.056640625,
                target: { scope: "all" },
                pose: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 132,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 276.69842694256755 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["zoom", "position"],
                easing: "linear",
                returnToDefault: false,
              },
              {
                id: "b082f142-792e-4c63-9dc4-886cd7065cbd",
                startMs: 1433.056640625,
                durationMs: 4046.826171875,
                target: { scope: "all" },
                pose: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 132,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: -374.59265906531533 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 132,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 276.69842694256755 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["position"],
                easing: "cubic",
                returnToDefault: false,
              },
              {
                id: "d17152cb-6a52-4e30-a8ef-479b72e88920",
                startMs: 5479.8828125,
                durationMs: 3014.74609375,
                target: { scope: "main" },
                pose: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 132,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: -374.59265906531533 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "none",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "image",
                    value:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    sourceUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=1080",
                    thumbUrl:
                      "https://images.unsplash.com/photo-1633547136812-6c4baeebbeda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MzIxNzl8MHwxfHNlYXJjaHw0fHx3aGl0ZSUyMGJhY2tncm91bmQlMjB3aXRoJTIwYmxhY2slMjBiYWxsc3xlbnwxfDB8fHwxNzg0OTEyMjAxfDA&ixlib=rb-4.1.0&q=80&w=400",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: { color: null, width: 1, style: "solid", padding: 0 },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["zoom", "position"],
                easing: "outCirc",
              },
            ],
          },
          id: "canvas-default",
          position: { x: 0, y: 0 },
          fullPageCapture: { scrollPosition: 0 },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: true,
    },
  },
}

export default uiShowcaseAnimated
