import type { Template } from "./types"
import { templateMeta } from "./catalog"

const zoomInReveal: Template = {
  ...templateMeta["zoom-in-reveal"],
  state: {
    schemaVersion: 1,
    present: {
      activeTool: "pointer",
      aspect: { id: "auto", w: 0, h: 0 },
      canvasZoom: 100,
      annotation: {
        mode: "pen",
        color: "#ef4444",
        strokeWidth: 4,
        lineStyle: "solid",
        blurEffect: "blur",
        blurAmount: 14,
      },
      canvases: [
        {
          screenshot: null,
          originalScreenshot: null,
          lastCropRegion: null,
          videoClips: null,
          background: {
            type: "auto",
            value: "linear-gradient(90deg, #c9c9c4, #b7b3ad)",
          },
          padding: 40,
          borderRadius: 7,
          canvasBorderRadius: 0,
          border: {
            color: "rgba(15,15,20,0.55)",
            width: 3,
            style: "solid",
            padding: 0,
          },
          backdrop: {
            effects: {
              noise: 0,
              blur: 0,
              brightness: 100,
              contrast: 100,
              saturation: 100,
              hue: 0,
              grayscale: 0,
              sepia: 0,
              invert: 0,
              opacity: 100,
            },
            pattern: {
              ids: [],
              intensity: 50,
              thickness: 1,
              color: "#FFFFFF",
            },
            lighting: {
              target: "inner",
              intensity: 0,
              direction: "0-0",
              color: "#FFFFFF",
            },
            filter: "none",
          },
          tilt: { rx: 0, ry: 0, rz: 0 },
          scale: 100,
          screenshotPosition: "center",
          screenshotOffset: { x: 0, y: 0 },
          objectFit: "contain",
          screenshotLayer: {
            zIndex: 2,
            opacity: 100,
            blendMode: "normal",
            hidden: false,
          },
          shadow: {
            type: "drop",
            intensity: 40,
            lightSource: "center",
            color: "#050505",
          },
          overlay: { id: null, opacity: 50, position: "overlay" },
          frame: { id: "none", color: "black", orientation: "vertical" },
          portrait: { mode: "off", intensity: 60, position: 50, distance: 50 },
          texts: [],
          assets: [],
          enhance: "off",
          annotations: [],
          annotationShapes: [],
          screenshotSlots: [],
          frameAddress: "",
          tweet: null,
          animation: {
            durationMs: 10300,
            clips: [
              {
                id: "0581e042-f8b2-4f75-a49a-54906fb056e0",
                startMs: 0,
                durationMs: 10289.208984375,
                target: { scope: "all" },
                pose: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 100,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "drop",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value: "linear-gradient(90deg, #c9c9c4, #b7b3ad)",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: {
                    color: "rgba(15,15,20,0.55)",
                    width: 3,
                    style: "solid",
                    padding: 0,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                baseline: {
                  tilt: { rx: 0, ry: 0, rz: 0 },
                  scale: 75,
                  screenshotPosition: "center",
                  screenshotOffset: { x: 0, y: 0 },
                  padding: 40,
                  canvasBorderRadius: 0,
                  shadow: {
                    type: "drop",
                    intensity: 40,
                    lightSource: "center",
                    color: "#050505",
                  },
                  backdropEffects: {
                    noise: 0,
                    blur: 0,
                    brightness: 100,
                    contrast: 100,
                    saturation: 100,
                    hue: 0,
                    grayscale: 0,
                    sepia: 0,
                    invert: 0,
                    opacity: 100,
                  },
                  lighting: {
                    target: "inner",
                    intensity: 0,
                    direction: "0-0",
                    color: "#FFFFFF",
                  },
                  background: {
                    type: "auto",
                    value: "linear-gradient(90deg, #c9c9c4, #b7b3ad)",
                  },
                  filter: "none",
                  portrait: {
                    mode: "off",
                    intensity: 60,
                    position: 50,
                    distance: 50,
                  },
                  pattern: {
                    ids: [],
                    intensity: 50,
                    thickness: 1,
                    color: "#FFFFFF",
                  },
                  overlay: { id: null, opacity: 50, position: "overlay" },
                  border: {
                    color: "rgba(15,15,20,0.55)",
                    width: 3,
                    style: "solid",
                    padding: 0,
                  },
                  borderRadius: 7,
                  crop: null,
                  slots: {},
                },
                effects: ["zoom"],
                easing: "linear",
              },
            ],
          },
          id: "canvas-default",
          position: { x: 0, y: 0 },
          fullPageCapture: { scrollPosition: 0 },
        },
      ],
      activeCanvasId: "canvas-default",
    },
    ui: {
      presetTab: "single",
      activeLayoutPresetId: null,
      activeCustomPresetId: null,
      activeSinglePresetId: null,
      bulkEditMode: false,
      bulkViewportZoom: 1,
      bulkScale: 65,
      previewAutoScrollDelay: 3000,
      previewAnimation: "slide",
      isAnimateMode: true,
    },
  },
}

export default zoomInReveal
